name: Deployment workflow
on:
  push:
    branches: [master]
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/jdav2k.github.io
            git pull
            rm -r ~/../pub/* -f
            cp -r ~/jdav2k.github.io/ ~/../pub/
